# echo hello
name: Echo hello

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  echo-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Echo hello
        run: echo "Hello, World!"
